from __future__ import annotations

REPORT_SCHEMA: dict = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": [
        "report_version",
        "overall_status",
        "contract_id",
        "review_status",
        "requires_human_review",
        "business_logic_review_required",
        "review_reason",
        "findings",
        "analysis_metadata",
        "security_score",
        "score_formula_version",
        "score_factors",
    ],
    "properties": {
        "report_version": {"type": "string"},
        "overall_status": {"enum": ["finding", "no_finding", "partial_analysis", "error"]},
        "contract_id": {"type": "string"},
        "review_status": {
            "enum": ["pending_human_review", "approved", "rejected", "blocked"]
        },
        "requires_human_review": {"type": "boolean"},
        "business_logic_review_required": {"type": "boolean"},
        "review_reason": {"type": "string"},
        "findings": {
            "type": "array",
            "items": {"$ref": "#/$defs/finding"},
        },
        "security_score": {"type": "number", "minimum": 0, "maximum": 100},
        "score_formula_version": {"type": "string"},
        "score_factors": {"type": "object"},
        "analysis_metadata": {
            "type": "object",
            "required": [
                "dataset_version",
                "model_version",
                "solc_version",
                "slither_version",
                "partial_analysis",
                "analysis_trace_id",
                "context_tokens_used",
                "prompt_tokens",
                "completion_tokens",
                "total_tokens",
                "local_average_judge_score",
                "external_average_judge_score",
                "rag_mode",
                "total_duration_ms",
                "input_kind",
                "project_type",
                "entry_path",
                "project_root",
                "source_files_count",
                "errors",
            ],
            "properties": {
                "dataset_version": {"type": "string"},
                "model_version": {"type": "string"},
                "solc_version": {"type": ["string", "null"]},
                "slither_version": {"type": ["string", "null"]},
                "partial_analysis": {"type": "boolean"},
                "analysis_trace_id": {"type": "string"},
                "context_tokens_used": {"type": "integer", "minimum": 0},
                "prompt_tokens": {"type": "integer", "minimum": 0},
                "completion_tokens": {"type": "integer", "minimum": 0},
                "total_tokens": {"type": "integer", "minimum": 0},
                "local_average_judge_score": {"type": "number", "minimum": 0, "maximum": 5},
                "external_average_judge_score": {"type": "number", "minimum": 0, "maximum": 5},
                "rag_mode": {"type": "string"},
                "total_duration_ms": {"type": "integer", "minimum": 0},
                "input_kind": {"type": "string"},
                "project_type": {"type": "string"},
                "entry_path": {"type": "string"},
                "project_root": {"type": "string"},
                "source_files_count": {"type": "integer", "minimum": 0},
                "errors": {"type": "array", "items": {"type": "string"}},
            },
        },
    },
    "$defs": {
        "finding": {
            "type": "object",
            "required": [
                "finding_id",
                "vulnerability_type",
                "severity",
                "location",
                "evidence",
                "reference",
                "finding_confidence",
                "explanation_confidence",
                "explanation",
                "attack_path",
                "fix_suggestion",
                "remediation_code",
                "vulnerable_code",
                "static_tool_source",
                "detector_name",
                "partial",
                "local_judge_score",
                "external_judge_score",
                "prompt_tokens",
                "completion_tokens",
                "total_tokens",
            ],
            "properties": {
                "finding_id": {"type": "string"},
                "vulnerability_type": {"type": "string"},
                "severity": {"type": "integer", "minimum": 1, "maximum": 3},
                "location": {
                    "type": "object",
                    "required": ["file", "function", "line_start", "line_end"],
                },
                "evidence": {"type": "string"},
                "reference": {"type": "array", "items": {"type": "string"}},
                "finding_confidence": {"type": "number", "minimum": 0, "maximum": 1},
                "explanation_confidence": {"type": "number", "minimum": 0, "maximum": 1},
                "explanation": {"type": "string"},
                "attack_path": {"type": "string"},
                "fix_suggestion": {"type": "string"},
                "remediation_code": {"type": "string"},
                "vulnerable_code": {"type": "string"},
                "static_tool_source": {"type": "string"},
                "detector_name": {"type": "string"},
                "partial": {"type": "boolean"},
                "local_judge_score": {"type": "number", "minimum": 0, "maximum": 5},
                "external_judge_score": {"type": "number", "minimum": 0, "maximum": 5},
                "prompt_tokens": {"type": "integer", "minimum": 0},
                "completion_tokens": {"type": "integer", "minimum": 0},
                "total_tokens": {"type": "integer", "minimum": 0},
            },
        }
    },
}
