from __future__ import annotations

REPORT_SCHEMA: dict = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": [
        "report_version",
        "overall_status",
        "contract_id",
        "review_status",
        "requires_human_review",
        "business_logic_review_required",
        "review_reason",
        "findings",
        "analysis_metadata",
        "security_score",
        "score_formula_version",
        "score_factors",
        "external_tool_results",
        "evidence_graph_summary",
    ],
    "properties": {
        "report_version": {"type": "string"},
        "overall_status": {"enum": ["finding", "no_finding", "partial_analysis", "error"]},
        "contract_id": {"type": "string"},
        "review_status": {
            "enum": ["pending_human_review", "approved", "rejected", "blocked"]
        },
        "requires_human_review": {"type": "boolean"},
        "business_logic_review_required": {"type": "boolean"},
        "review_reason": {"type": "string"},
        "findings": {
            "type": "array",
            "items": {"$ref": "#/$defs/finding"},
        },
        "security_score": {"type": "number", "minimum": 0, "maximum": 100},
        "score_formula_version": {"type": "string"},
        "score_factors": {"type": "object"},
        "external_tool_results": {
            "type": "array",
            "items": {"$ref": "#/$defs/external_tool_result"},
        },
        "evidence_graph_summary": {"type": "object"},
        "analysis_metadata": {
            "type": "object",
            "required": [
                "dataset_version",
                "model_version",
                "solc_version",
                "slither_version",
                "partial_analysis",
                "analysis_trace_id",
                "context_tokens_used",
                "prompt_tokens",
                "completion_tokens",
                "total_tokens",
                "local_average_judge_score",
                "external_average_judge_score",
                "rag_mode",
                "total_duration_ms",
                "input_kind",
                "project_type",
                "entry_path",
                "project_root",
                "source_files_count",
                "errors",
            ],
            "properties": {
                "dataset_version": {"type": "string"},
                "model_version": {"type": "string"},
                "solc_version": {"type": ["string", "null"]},
                "slither_version": {"type": ["string", "null"]},
                "partial_analysis": {"type": "boolean"},
                "analysis_trace_id": {"type": "string"},
                "context_tokens_used": {"type": "integer", "minimum": 0},
                "prompt_tokens": {"type": "integer", "minimum": 0},
                "completion_tokens": {"type": "integer", "minimum": 0},
                "total_tokens": {"type": "integer", "minimum": 0},
                "local_average_judge_score": {"type": "number", "minimum": 0, "maximum": 5},
                "external_average_judge_score": {"type": "number", "minimum": 0, "maximum": 5},
                "rag_mode": {"type": "string"},
                "total_duration_ms": {"type": "integer", "minimum": 0},
                "input_kind": {"type": "string"},
                "project_type": {"type": "string"},
                "entry_path": {"type": "string"},
                "project_root": {"type": "string"},
                "source_files_count": {"type": "integer", "minimum": 0},
                "errors": {"type": "array", "items": {"type": "string"}},
            },
        },
    },
    "$defs": {
        "finding": {
            "type": "object",
            "required": [
                "finding_id",
                "vulnerability_type",
                "severity",
                "location",
                "evidence",
                "reference",
                "finding_confidence",
                "explanation_confidence",
                "explanation",
                "attack_path",
                "fix_suggestion",
                "remediation_code",
                "vulnerable_code",
                "static_tool_source",
                "detector_name",
                "partial",
                "local_judge_score",
                "external_judge_score",
                "prompt_tokens",
                "completion_tokens",
                "total_tokens",
                "review_status",
                "review_note",
                "standard_refs",
                "evidence_graph",
                "native_rule_results",
                "exploit_validation",
                "fuzz_seed_suggestions",
                "formal_property_suggestions",
                "defi_profit_signal",
            ],
            "properties": {
                "finding_id": {"type": "string"},
                "vulnerability_type": {"type": "string"},
                "severity": {"type": "integer", "minimum": 1, "maximum": 3},
                "location": {
                    "type": "object",
                    "required": ["file", "function", "line_start", "line_end"],
                },
                "evidence": {"type": "string"},
                "reference": {"type": "array", "items": {"type": "string"}},
                "finding_confidence": {"type": "number", "minimum": 0, "maximum": 1},
                "explanation_confidence": {"type": "number", "minimum": 0, "maximum": 1},
                "explanation": {"type": "string"},
                "attack_path": {"type": "string"},
                "fix_suggestion": {"type": "string"},
                "remediation_code": {"type": "string"},
                "vulnerable_code": {"type": "string"},
                "static_tool_source": {"type": "string"},
                "detector_name": {"type": "string"},
                "partial": {"type": "boolean"},
                "local_judge_score": {"type": "number", "minimum": 0, "maximum": 5},
                "external_judge_score": {"type": "number", "minimum": 0, "maximum": 5},
                "prompt_tokens": {"type": "integer", "minimum": 0},
                "completion_tokens": {"type": "integer", "minimum": 0},
                "total_tokens": {"type": "integer", "minimum": 0},
                "review_status": {
                    "enum": [
                        "unreviewed",
                        "true_positive",
                        "false_positive",
                        "accepted_risk",
                        "fixed",
                    ]
                },
                "review_note": {"type": "string"},
                "standard_refs": {
                    "type": "array",
                    "items": {"$ref": "#/$defs/standard_ref"},
                },
                "evidence_graph": {"type": "object"},
                "native_rule_results": {
                    "type": "array",
                    "items": {"type": "object"},
                },
                "exploit_validation": {"$ref": "#/$defs/exploit_validation"},
                "fuzz_seed_suggestions": {
                    "type": "array",
                    "items": {"$ref": "#/$defs/fuzz_seed"},
                },
                "formal_property_suggestions": {
                    "type": "array",
                    "items": {"$ref": "#/$defs/formal_property"},
                },
                "defi_profit_signal": {"type": "object"},
            },
        },
        "exploit_validation": {
            "type": "object",
            "required": [
                "status",
                "mode",
                "human_review_required",
                "safety_notes",
                "supported_by",
            ],
            "properties": {
                "status": {
                    "enum": [
                        "not_attempted",
                        "generated",
                        "executed_triggered",
                        "executed_not_triggered",
                        "failed_to_compile",
                        "failed_to_run",
                        "blocked_by_policy",
                        "requires_human_review",
                    ]
                },
                "mode": {"type": "string"},
                "poc_artifact_path": {"type": ["string", "null"]},
                "test_framework": {"type": ["string", "null"]},
                "triggered": {"type": ["boolean", "null"]},
                "profit_delta": {"type": ["object", "null"]},
                "asset_delta": {"type": "array", "items": {"type": "object"}},
                "transaction_sequence": {"type": "array"},
                "execution_log_path": {"type": ["string", "null"]},
                "human_review_required": {"type": "boolean"},
                "safety_notes": {"type": "array", "items": {"type": "string"}},
                "supported_by": {"type": "array", "items": {"type": "string"}},
            },
        },
        "fuzz_seed": {
            "type": "object",
            "required": ["finding_id", "seed_id", "target_function", "supported_by"],
            "properties": {
                "finding_id": {"type": "string"},
                "seed_id": {"type": "string"},
                "target_function": {"type": "string"},
                "preconditions": {"type": "array", "items": {"type": "string"}},
                "sequence": {"type": "array"},
                "expected_signal": {"type": "string"},
                "status": {"type": "string"},
                "supported_by": {"type": "array", "items": {"type": "string"}},
            },
        },
        "formal_property": {
            "type": "object",
            "required": [
                "property_id",
                "finding_id",
                "format",
                "status",
                "verification_status",
                "supported_by",
            ],
            "properties": {
                "property_id": {"type": "string"},
                "finding_id": {"type": "string"},
                "format": {"type": "string"},
                "status": {"const": "draft"},
                "property_text": {"type": "string"},
                "compile_status": {"type": "string"},
                "verification_status": {"type": "string"},
                "supported_by": {"type": "array", "items": {"type": "string"}},
                "review_notes": {"type": "string"},
            },
        },
        "standard_ref": {
            "type": "object",
            "required": ["standard", "id", "label", "confidence"],
            "properties": {
                "standard": {"type": "string"},
                "id": {"type": "string"},
                "label": {"type": "string"},
                "confidence": {"type": "string"},
            },
        },
        "external_tool_result": {
            "type": "object",
            "required": [
                "tool_name",
                "command",
                "status",
                "findings_count",
                "summary",
                "execution_mode",
                "binary_path",
                "timeout_seconds",
                "output_path",
                "artifact_paths",
                "error",
                "duration_ms",
            ],
            "properties": {
                "tool_name": {"type": "string"},
                "command": {"type": "array", "items": {"type": "string"}},
                "status": {"enum": ["skipped", "passed", "finding", "error"]},
                "findings_count": {"type": "integer", "minimum": 0},
                "summary": {"type": "string"},
                "execution_mode": {"type": "string"},
                "binary_path": {"type": "string"},
                "timeout_seconds": {"type": "integer", "minimum": 0},
                "output_path": {"type": "string"},
                "artifact_paths": {
                    "type": "object",
                    "additionalProperties": {"type": "string"},
                },
                "error": {"type": "string"},
                "duration_ms": {"type": "integer", "minimum": 0},
            },
        },
    },
}
